# Generated by Django 5.0.3 on 2024-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.TextField(blank=True, null=True, verbose_name='id чата в телеге'),
        ),
    ]
