# Generated by Django 5.0.3 on 2024-03-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='имя в телеге'),
        ),
    ]
