# Generated by Django 5.0.3 on 2024-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
